(function(){
  const files=[
    ['README.md','Project overview'],['index.html','Entry page'],['story.html','Project story'],['style.css','Entry styles'],['vellomo-brand.js','Brand runtime'],
    ['home/index.html','Main website'],['home/style.css','Main website styles'],['home/config.js','Live service configuration'],['home/javascript/woodoodata.js','Live metrics renderer'],['home/javascript/woodoochat.js','Realtime chat'],['home/javascript/guestbook.js','Guestbook client'],
    ['bot/README.md','Bot documentation'],['bot/package.json','Bot package manifest'],['bot/bot.js','Autonomous builder'],['bot/cam-capture.js','Camera capture service'],['bot/ai.config.example.json','AI configuration example']
  ];
  const tree=document.getElementById('fileTree'),view=document.getElementById('codeView'),active=document.getElementById('activePath'),meta=document.getElementById('fileMeta'),raw=document.getElementById('rawLink'),search=document.getElementById('repoSearch'),copy=document.getElementById('copyCode');let source='';
  document.getElementById('fileCount').textContent=`${files.length} files`;
  function icon(path){return /\.(js|json)$/.test(path)?'◇':/\.css$/.test(path)?'◆':/\.html$/.test(path)?'▱':'▤'}
  function renderTree(filter=''){tree.replaceChildren();files.filter(([path,description])=>`${path} ${description}`.toLowerCase().includes(filter.toLowerCase())).forEach(([path])=>{const button=document.createElement('button');button.className='file-row';button.dataset.path=path;button.innerHTML=`<b>${icon(path)}</b><span>${path}</span>`;button.addEventListener('click',()=>openFile(path));tree.append(button)});if(!tree.children.length)tree.innerHTML='<div class="empty">No matching files</div>'}
  async function openFile(path){active.textContent=path;raw.href=path;view.innerHTML='<div class="empty">Loading source…</div>';document.querySelectorAll('.file-row').forEach(row=>row.classList.toggle('active',row.dataset.path===path));try{const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);source=await response.text();const lines=source.replace(/\r\n/g,'\n').split('\n'),table=document.createElement('table');table.className='code-table';const body=document.createElement('tbody');lines.forEach((line,index)=>{const row=document.createElement('tr'),number=document.createElement('td'),code=document.createElement('td');number.className='line-number';number.textContent=index+1;code.className='code-line';code.textContent=line||' ';row.append(number,code);body.append(row)});table.append(body);view.replaceChildren(table);meta.textContent=`${lines.length.toLocaleString()} lines · ${new Blob([source]).size.toLocaleString()} bytes`;history.replaceState(null,'',`repository.html?file=${encodeURIComponent(path)}`)}catch(error){source='';meta.textContent='Unable to load file';view.innerHTML=`<div class="empty">${error.message}</div>`}}
  search.addEventListener('input',()=>renderTree(search.value));copy.addEventListener('click',async()=>{if(!source)return;await navigator.clipboard.writeText(source);copy.textContent='Copied!';setTimeout(()=>copy.textContent='Copy raw file',1200)});
  renderTree();const requested=new URLSearchParams(location.search).get('file'),initial=files.some(([path])=>path===requested)?requested:'README.md';openFile(initial);
})();
